### ISSUE TITLE
Pokemon in Readme doesn't look enough like a pomeranian

### ISSUE THREAD

**Issue by russmatney** [jenwilhelm/pokemon_ios#1]
Would appreciate an update to something more like this:

![growlithe](https://cloud.githubusercontent.com/assets/1596350/4431655/dd567770-4671-11e4-9250-c27944cc7154.png)

**Comment by jimmyjacobson** [comment]
@russmatney can you please mark this as resolved?

**Comment by jenwilhelm** [comment]
![image](https://cloud.githubusercontent.com/assets/223514/9855535/aba1105c-5ac3-11e5-8f66-e5b13f9272bb.png)

**Comment by russmatney** [comment]
The stakes have been raised. I will not settle for any cartoons in the Readme when pokemon have been proven to exist via pictures akin to the above. Please update the Readme and plans for the app accordingly.

**Comment by jenwilhelm** [comment]
@russmatney better?

**Comment by russmatney** [comment]
MUCH.
